routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WebController@beranda')->name('beranda');
Route::get('/kamar/{slug}', 'WebController@kamar')->name('kamar');
Route::get('/detail-kamar/{id}', 'WebController@detailKamar')->name('detail.kamar');
Route::get('/tentang-kami', 'WebController@tentangKami')->name('tentang.kami');
Route::get('/amenities', 'WebController@amenities')->name('amenities');
Route::get('/berita', 'WebController@berita')->name('berita');
Route::get('/kontak-kami', 'WebController@kontakKami')->name('kontak.kami');
Route::post('/kontak-kami', 'WebController@postKontak')->name('post.kontak.kami');
Route::get('/login', 'WebController@login')->name('custom.login');
Route::get('/daftar-baru', 'WebController@daftar')->name('daftar.baru');
Route::post('/daftar-baru', 'WebController@postDaftar')->name('post.daftar.baru');
Route::post('/login', 'WebController@postLogin')->name('post.login');


Route::group(['middleware' => ['auth', 'checkRole:admin'], 'prefix' => 'admin'], function() {
    Route::get('dashboard', 'AdminAjaxController@tampilDashboard')->name('dashboard');

    Route::group(['prefix' => 'kategori'], function() {
        Route::resource('ajax-kategori-kamar','KategoriKamarAjaxController');
        Route::resource('ajax-kategori-layanan','KategoriLayananAjaxController');
    });

    Route::group(['prefix' => 'master'], function() {
        Route::resource('ajax-master-satuan','MasterSatuanAjaxController');
        Route::resource('ajax-master-kamar','MasterKamarAjaxController');
        Route::resource('ajax-master-layanan','MasterLayananAjaxController');
        Route::resource('ajax-master-user','MasterUserAjaxController');
        Route::resource('ajax-master-slider', 'MasterSliderAjaxController');
    });

    Route::group(['prefix' => 'transaksi'], function() {
        Route::resource('ajax-master-transaksi-kamar', 'MasterTransaksiKamarAjaxController');
    });

    Route::group(['prefix' => 'kontak'], function() {
        Route::resource('ajax-kontak', 'KontakAjaxController');
    });

    //table
    Route::get('/ajax/tabel-ajax-kategori-kamar', 'KategoriKamarAjaxController@dataTable')->name('table.ajax.kategori.kamar');
    Route::get('/ajax/tabel-ajax-kategori-layanan', 'KategoriLayananAjaxController@dataTable')->name('table.ajax.kategori.layanan');
    Route::get('/ajax/tabel-ajax-satuan', 'MasterSatuanAjaxController@dataTable')->name('table.ajax.satuan');
    Route::get('/ajax/tabel-ajax-kamar', 'MasterKamarAjaxController@dataTable')->name('table.ajax.master.kamar');
    Route::get('/ajax/tabel-ajax-layanan', 'MasterLayananAjaxController@dataTable')->name('table.ajax.master.layanan');
    Route::get('/ajax/tabel-ajax-slider', 'MasterSliderAjaxController@dataTable')->name('table.ajax.master.slider');
    Route::get('/ajax/tabel-ajax.user', 'MasterUserAjaxController@dataTable')->name('table.ajax.master.user');
    Route::get('/ajax/tabel-ajax-kontak', 'KontakAjaxController@dataTable')->name('table.ajax.kontak');
    Route::get('/ajax/tabel-ajax-transaksi-kamar', 'MasterTransaksiKamarAjaxController@dataTable')->name('table.ajax.transaksi.kamar');

    //lain-lain
    Route::post('/dapatkan-info-kategori-kamar', 'KategoriKamarAjaxController@dapatkanInfoKategoriKamar');
    Route::post('/dapatkan-data-kamar', 'MasterKamarAjaxController@dapatkanDataKamar');
    Route::post('/dapatkan-data-layanan', 'MasterLayananAjaxController@dapatkanDataLayanan');
    Route::post('/dapatkan-data-user', 'MasterUserAjaxController@dapatkanDataUser');
    Route::post('/dapatkan-data-slider', 'MasterSliderAjaxController@dapatkanDataSlider');
    Route::post('/cari-detail-kamar', 'KategoriKamarAjaxController@cariDetailKamar');
    Route::post('/dapatkan-data-tipe-transaksi', 'MasterTransaksiKamarAjaxController@dapatkanDataTipeTransaksi');
    Route::post('/validasi-detail-transaksi', 'MasterTransaksiKamarAjaxController@validasiDetailTransaksi');
    Route::post('/dapatkan-data-transaksi-user', 'MasterTransaksiKamarAjaxController@dapatkanDataTransaksiUser');
    Route::post('/dapatkan-data-transaksi-detail', 'MasterTransaksiKamarAjaxController@dapatkanDataTransaksiDetail');

    //print
    Route::get('/cetak-transaksi-kamar/{id}/cetak-deskjet', 'MasterTransaksiKamarAjaxController@cetakDeskjet')->name('ajax-master-transaksi-kamar.cetak.deskjet');
    Route::get('/testing-laravel-javascript', 'MasterKamarAjaxController@testingLaravelJavascript');
});



Route::group(['middleware' => ['auth']], function() {
    Route::get('/logout', 'WebController@logout')->name('logout');
});

Route::get('/test', function () {
    $x = 1;
    $y = 2;
    $z = 3;
    return 'test';
});

Route::get('tanggal', function() {
    $date = date("D M d, Y G:i");
    return formatTanggal($date);
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $table = 'slider';
    protected $fillable = ['tag', 'judul', 'gambar', 'link'];
}

resources/views/admin/master/slider/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['ajax-master-slider.update', $model->id] : 'ajax-master-slider.store',
    'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

<div class="card mb-2">
    <div class="card-header bg-dark">
        <h6 class="font-weight-bold">Input Data Slider</h6>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-12">
                <div class="form-group">
                    {!! Form::text('tag', null, ['class' => 'form-control form-control-sm', 'id' => 'tag', 
                        'placeholder' => 'Masukkan Nama Tag']) !!}
                </div>
                <div class="form-group">
                    {!! Form::text('judul', null, ['class' => 'form-control form-control-sm', 
                        'id' => 'judul', 'placeholder' => 'Masukkan Judul']) !!}
                </div>
                <div class="form-group">
                    {!! Form::text('link', null, ['class' => 'form-control form-control-sm', 'id' => 'link', 
                       'placeholder' => 'Masukkan Link']) !!}
                </div>
                <div class="form-group">
                    {!! Form::file('file', ['id' => 'file', 'class' => 'form-control form-control-sm']) !!}
                </div>
                @if($model->exists)
                    {!! Form::hidden('nama_file_lama', $model->gambar) !!}
                @endif
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header bg-dark">
        <h6 class="font-weight-bold">Gambar</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <img id="data_gambar" src="{{ url('/images/sliders/unknown.jpg') }}" />
            </div>
        </div>
    </div>
</div>




{!! Form::close() !!}

resources/views/admin/master/slider/index.blade.php
@extends('layouts.admin')
@section('title', 'Data Slider')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="card border-danger">
            <div class="card-header">
                <h3 class="card-title">List Gambar Slider</h3>
                <div class="card-tools">
                    <a class="btn btn-sm btn-success btn-tampil-modal" data-toggle="modal" tipe="tambah" 
                        judul="Tambah Gambar Slider Baru"
                        href="{{ route('ajax-master-slider.create') }}">
                        <i class="fa fa-plus"></i></a>
                </div>
            </div>
            <div class="card-body">
                <table id="dataTable" class="table table-sm table-hover tabel-master-slider">
                    <thead>
                        <tr>
                            <th>Gambar</th>
                            <th>Judul</th>
                            <th>Tag</th>
                            <th>Link</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(document).ready(function() {
    $('#dataTable').DataTable({
        autoWidth: false,
        serverSide: true,
        processing: true,
        responsive: true,
        ajax: "{{ route('table.ajax.master.slider') }}",
        columns: [
            { data: 'gambar', nama: 'gambar', render:function(data, tipe, row) {
                return "<img src='/images/sliders/" + data + "'>";
            }}, 
            { data: 'judul', name: 'judul' },
            { data: 'tag', name: 'tag' },
            { data: 'link', name: 'link', render:function(data, tipe, row) {
                return "<a onclick='window.location.href='" + window.location.host + "/" + data + "' target='_blank'>"  + data + "</a>";
            } },
            { data: 'aksi', name: 'aksi' }
        ],
        language: {
            lengthMenu: 'Tampil _MENU_ rekord per halaman',
            info: 'Tampil hal _PAGE_ dari _PAGES_',
            processing: 'Sedang memproses...',
            search: 'Cari',
            zeroRecords: 'Tidak ditemukan rekord',
            paginate: {
                first: '<<',
                last: '>>',
                next: '>',
                previous: '<',
            },
            infoFiltered: "( filter dari _MAX_ jumlah rekord )"
        }
    })

    $('body').on('change', '#file', function(E) {
        bacaUrl(this);
    });    

    $('#modal').on('shown.bs.modal', function(e){
        var status = $('#modal').attr('tipe');
        if (status === 'edit') {
            var sliderId = $('#modal').attr('kode');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            //cari data slider
            $.ajax({
                url: '/admin/dapatkan-data-slider',
                data: { sliderId },
                type: 'POST',
                success: function(res) {
                    var slider = res;
                    gambar = slider.gambar;
                    $('#data_gambar').attr('src', '/images/sliders/' + gambar);
                },
                error: function(e) {
                    console.log(e);
                }
            });
        }               
    });
})
</script>
@endpush

resources/views/admin/master/slider/tampil.blade.php
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header bg-primary">
                <h6 class="font-weight-bold">Data Slider</h6>
            </div>
            <div class="card-body">
                <table class="table table-borderless tabel-master-show tabel-tampil-kamar">
                    <tbody>
                        <tr>
                            <td>Tag</td>
                            <td>:</td>
                            <td>{{ $model->tag }}</td>
                        </tr>
                        <tr>
                            <td>Judul</td>
                            <td>:</td>
                            <td>{{ $model->judul }}</td>
                        </tr>
                        <tr>
                            <td>Link</td>
                            <td>:</td>
                            <td>{{ $model->link }}</td>
                        </tr>
                        <tr>
                            <td>Gambar</td>
                            <td>:</td>
                            <td><img src="{{ url('/images/sliders/' . $model->gambar) }}"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>