routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WebController@beranda')->name('beranda');
Route::get('/kamar/{slug}', 'WebController@kamar')->name('kamar');
Route::get('/detail-kamar/{id}', 'WebController@detailKamar')->name('detail.kamar');
Route::get('/tentang-kami', 'WebController@tentangKami')->name('tentang.kami');
Route::get('/amenities', 'WebController@amenities')->name('amenities');
Route::get('/berita', 'WebController@berita')->name('berita');
Route::get('/kontak-kami', 'WebController@kontakKami')->name('kontak.kami');
Route::post('/kontak-kami', 'WebController@postKontak')->name('post.kontak.kami');
Route::get('/login', 'WebController@login')->name('custom.login');
Route::get('/daftar-baru', 'WebController@daftar')->name('daftar.baru');
Route::post('/daftar-baru', 'WebController@postDaftar')->name('post.daftar.baru');
Route::post('/login', 'WebController@postLogin')->name('post.login');


Route::group(['middleware' => ['auth', 'checkRole:admin'], 'prefix' => 'admin'], function() {
    Route::get('dashboard', 'AdminAjaxController@tampilDashboard')->name('dashboard');

    Route::group(['prefix' => 'kategori'], function() {
        Route::resource('ajax-kategori-kamar','KategoriKamarAjaxController');
        Route::resource('ajax-kategori-layanan','KategoriLayananAjaxController');
    });

    Route::group(['prefix' => 'master'], function() {
        Route::resource('ajax-master-satuan','MasterSatuanAjaxController');
        Route::resource('ajax-master-kamar','MasterKamarAjaxController');
        Route::resource('ajax-master-layanan','MasterLayananAjaxController');
        Route::resource('ajax-master-user','MasterUserAjaxController');
        Route::resource('ajax-master-slider', 'MasterSliderAjaxController');
    });

    Route::group(['prefix' => 'transaksi'], function() {
        Route::resource('ajax-master-transaksi-kamar', 'MasterTransaksiKamarAjaxController');
    });

    Route::group(['prefix' => 'kontak'], function() {
        Route::resource('ajax-kontak', 'KontakAjaxController');
    });

    //table
    Route::get('/ajax/tabel-ajax-kategori-kamar', 'KategoriKamarAjaxController@dataTable')->name('table.ajax.kategori.kamar');
    Route::get('/ajax/tabel-ajax-kategori-layanan', 'KategoriLayananAjaxController@dataTable')->name('table.ajax.kategori.layanan');
    Route::get('/ajax/tabel-ajax-satuan', 'MasterSatuanAjaxController@dataTable')->name('table.ajax.satuan');
    Route::get('/ajax/tabel-ajax-kamar', 'MasterKamarAjaxController@dataTable')->name('table.ajax.master.kamar');
    Route::get('/ajax/tabel-ajax-layanan', 'MasterLayananAjaxController@dataTable')->name('table.ajax.master.layanan');
    Route::get('/ajax/tabel-ajax-slider', 'MasterSliderAjaxController@dataTable')->name('table.ajax.master.slider');
    Route::get('/ajax/tabel-ajax.user', 'MasterUserAjaxController@dataTable')->name('table.ajax.master.user');
    Route::get('/ajax/tabel-ajax-kontak', 'KontakAjaxController@dataTable')->name('table.ajax.kontak');
    Route::get('/ajax/tabel-ajax-transaksi-kamar', 'MasterTransaksiKamarAjaxController@dataTable')->name('table.ajax.transaksi.kamar');

    //lain-lain
    Route::post('/dapatkan-info-kategori-kamar', 'KategoriKamarAjaxController@dapatkanInfoKategoriKamar');
    Route::post('/dapatkan-data-kamar', 'MasterKamarAjaxController@dapatkanDataKamar');
    Route::post('/dapatkan-data-layanan', 'MasterLayananAjaxController@dapatkanDataLayanan');
    Route::post('/dapatkan-data-user', 'MasterUserAjaxController@dapatkanDataUser');
    Route::post('/dapatkan-data-slider', 'MasterSliderAjaxController@dapatkanDataSlider');
    Route::post('/cari-detail-kamar', 'KategoriKamarAjaxController@cariDetailKamar');
    Route::post('/dapatkan-data-tipe-transaksi', 'MasterTransaksiKamarAjaxController@dapatkanDataTipeTransaksi');
    Route::post('/validasi-detail-transaksi', 'MasterTransaksiKamarAjaxController@validasiDetailTransaksi');
    Route::post('/dapatkan-data-transaksi-user', 'MasterTransaksiKamarAjaxController@dapatkanDataTransaksiUser');
    Route::post('/dapatkan-data-transaksi-detail', 'MasterTransaksiKamarAjaxController@dapatkanDataTransaksiDetail');

    //print
    Route::get('/cetak-transaksi-kamar/{id}/cetak-deskjet', 'MasterTransaksiKamarAjaxController@cetakDeskjet')->name('ajax-master-transaksi-kamar.cetak.deskjet');
    Route::get('/testing-laravel-javascript', 'MasterKamarAjaxController@testingLaravelJavascript');
});



Route::group(['middleware' => ['auth']], function() {
    Route::get('/logout', 'WebController@logout')->name('logout');
});

Route::get('/test', function () {
    $x = 1;
    $y = 2;
    $z = 3;
    return 'test';
});

Route::get('tanggal', function() {
    $date = date("D M d, Y G:i");
    return formatTanggal($date);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama_lengkap', 'email', 'password', 'alamat', 'kota', 'no_telpon',
            'kodepos', 'jenkel', 'role', 'verifikasi_token', 'gambar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'verifikasi_token',
    ];

    protected $casts = [
        'status_verifikasi' => 'boolean',
    ];

    public function setTokenVerifikasi() {
        $token = Str::random(60);
        $this->verifikasi_token = $token;
        $this->save();
    }

    public function verifikasi() {
        if ($this->status_verifikasi) {
            return 'sudah terverifikasi';
        } else {
            return 'belum terverifikasi';
        }
    }

    public function transaksi_kamar() {
        return $this->hasMany(TransaksiKamar::class);
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];
}

resources/views/admin/master/user/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['ajax-master-user.update', $model->id] : 'ajax-master-user.store',
    'method' => $model->exists ? 'PUT' : 'POST',
    'novalidate' => 'novalidate',
    'files' => 'true'
]) !!}

<div class="card mb-2">
    <div class="card-header bg-dark">
        <h6 class="font-weight-bold">Input Data User</h6>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::text('nama_lengkap', null, ['class' => 'form-control form-control-sm',
                    'id' => 'nama_lengkap', 'placeholder' => 'Masukkan Nama Lengkap']) !!}
                </div>
                <div class="form-group">
                    {!! Form::Email('email', null, ['class' => 'form-control form-control-sm',
                    'id' => 'email', 'placeholder' => 'Masukkan Email']) !!}
                </div>
                @if(!$model->exists)
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                {!! Form::password('password', ['id' => 'password', 'class' => 'form-control form-control-sm',
                                    'placeholder' => 'Masukkan Password']) !!}
                            </div>
                            <div class="col-md-6">
                                {!! Form::password('password_confirmation', ['class' => 'form-control form-control-sm',
                                    'placeholder' => 'Konfirmasi Password']) !!}
                            </div>
                        </div>
                    </div>
                @endif
                <div class="form-group">
                    {!! Form::textarea('alamat', null, ['id' => 'alamat', 'placeholder' => 'Masukkan Alamat',
                    'class' => 'form-control form-control-sm', 'rows' => 3]) !!}
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            {!! Form::select('kota', $kota, null, ['id' => 'kota', 'class' => 'form-control form-control-sm']) !!}
                        </div>
                        <div class="col-md-6">
                            {!! Form::text('kodepos', null, ['id' => 'kodepos', 'class' => 'form-control form-control-sm',
                                'placeholder' => 'Masukkan Kode Pos']) !!}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            {!! Form::select('jenkel', $jenkel, null, ['id' => 'jenkel', 'class' => 'form-control form-control-sm']) !!}
                        </div>
                        <div class="col-md-6">
                            {!! Form::text('no_telpon', null, ['id' => 'no_telpon', 'class' => 'form-control form-control-sm',
                            'placeholder'  => 'No Telpon']) !!}
                        </div>
                    </div>
               </div>
                <div class="form-group">
                    {!! Form::file('file', ['id' => 'file', 'class' => 'form-control form-control-sm']) !!}
                </div>
                @if($model->exists)
                    {!! Form::hidden('nama_file_lama', $model->gambar) !!}
                @endif
                <div class="card">
                    <div class="card-header bg-dark">
                    <h6 class="font-weight-bold">Gambar</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <img id="data_gambar" src="{{ url('/images/persons/unknown.jpg') }}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!}

resources/views/admin/master/user/index.blade.php
@extends('layouts.admin')
@section('title', 'Data Master User')

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card border-danger">
            <div class="card-header">
                <h3 class="card-title">List User</h3>
                <div class="card-tools">
                    <a class="btn btn-sm btn-success btn-tampil-modal" data-toggle="modal" tipe="tambah"
                        judul="Tambah User Baru" ukuran="besar"
                    href="{{ route('ajax-master-user.create') }}">
                        <i class="fa fa-plus"></i></a>
                </div>
            </div>
            <div class="card-body">
                <table id="dataTable" class="table table-sm table-hover tabel-master-user">
                    <thead>
                        <tr>
                            <th>Photo</th>
                            <th>Nama</th>
                            <th>Kota</th>
                            <th>No Telpon</th>
                            <th>Role</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                autoWidth: false,
                serverSide: true,
                processing: true,
                responsive: true,
                ajax: "{{ route('table.ajax.master.user') }}",
                columns: [
                    { data: 'gambar', nama: 'gambar', render:function(data, tipe, row) {
                        return "<img src='/images/persons/" + data + "'>";
                    },
                    orderable: false },
                    { data: 'nama_lengkap', name: 'nama_lengkap' },
                    { data: 'kota', name: 'kota' },
                    { data: 'no_telpon', name: 'no_telphon'},
                    { data: 'role', name: 'role' },
                    { data: 'aksi', name: 'aksi' }
                ],
                language: {
                    lengthMenu: 'Tampil _MENU_ rekord per halaman',
                    info: 'Tampil hal _PAGE_ dari _PAGES_',
                    processing: 'Sedang memproses...',
                    search: 'Cari',
                    zeroRecords: 'Tidak ditemukan rekord',
                    paginate: {
                        first: '<<',
                        last: '>>',
                        next: '>',
                        previous: '<',
                    },
                    infoFiltered: "( filter dari _MAX_ jumlah rekord )"
                }
            })

            $('body').on('change', '#kategori_kamar_id', function(e) {
                e.preventDefault();
                if ($(this).val() !== '') {
                    var kategoriId = $(this).val();
                    tampilInfoKategoriKamar(kategoriId);
                }
            });

            $('body').on('change', '#file', function(E) {
                bacaUrl(this);
            });

            $('#modal').on('shown.bs.modal', function(e){
                var status = $('#modal').attr('tipe');
                if (status === 'edit') {
                    var userId = $('#modal').attr('kode');

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    $.ajax({
                        url: '/admin/dapatkan-data-user',
                        data: { userId },
                        type: 'POST',
                        success: function(res) {
                            var user = res;
                            gambar = user.gambar;
                            $('#data_gambar').attr('src', '/images/persons/' + gambar);
                        },
                        error: function(e) {
                            console.log(e);
                        }
                    });
                }
            });
        });

        $('body').on('keyup', '#harga', function(e) {
            e.preventDefault();
            $('#harga').val(formatAngka($(this).val()));

            //bikin hidden value
            var integerHarga = accounting.unformat($(this).val());
            bikinHiddenInput('hidden_harga', integerHarga);
        });


    </script>
@endpush

resources/views/admin/master/user/tampil.blade.php
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header bg-primary">
                <h6 class="font-weight-bold">Data User</h6>
            </div>
            <div class="card-body">
                <table class="table table-borderless tabel-master-show tabel-tampil-kamar">
                    <tbody>
                        <tr>
                            <td>Nama Lengkap</td>
                            <td>:</td>
                            <td>{{ $model->nama_lengkap }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>:</td>
                            <td>{{ $model->email }}</td>
                        </tr>
                        <tr>
                            <td>Alamat</td>
                            <td>:</td>
                            <td>{{ $model->alamat }}</td>
                        </tr>
                        <tr>
                            <td>Kota</td>
                            <td>:</td>
                            <td>{{ $model->kota }}</td>
                        </tr>
                        <tr>
                            <td>No Telpon</td>
                            <td>:</td>
                            <td>{{ $model->no_telpon }}</td>
                        </tr>
                        <tr>
                            <td>Photo</td>
                            <td>:</td>
                            <td><img src="{{ url('/images/persons/' . $model->gambar) }}"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>