routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'WebController@beranda')->name('beranda');
Route::get('/kamar/{slug}', 'WebController@kamar')->name('kamar');
Route::get('/detail-kamar/{id}', 'WebController@detailKamar')->name('detail.kamar');
Route::get('/tentang-kami', 'WebController@tentangKami')->name('tentang.kami');
Route::get('/amenities', 'WebController@amenities')->name('amenities');
Route::get('/berita', 'WebController@berita')->name('berita');
Route::get('/kontak-kami', 'WebController@kontakKami')->name('kontak.kami');
Route::post('/kontak-kami', 'WebController@postKontak')->name('post.kontak.kami');
Route::get('/login', 'WebController@login')->name('custom.login');
Route::get('/daftar-baru', 'WebController@daftar')->name('daftar.baru');
Route::post('/daftar-baru', 'WebController@postDaftar')->name('post.daftar.baru');
Route::post('/login', 'WebController@postLogin')->name('post.login');


Route::group(['middleware' => ['auth', 'checkRole:admin'], 'prefix' => 'admin'], function() {
    Route::get('dashboard', 'AdminAjaxController@tampilDashboard')->name('dashboard');

    Route::group(['prefix' => 'kategori'], function() {
        Route::resource('ajax-kategori-kamar','KategoriKamarAjaxController');
        Route::resource('ajax-kategori-layanan','KategoriLayananAjaxController');
    });

    Route::group(['prefix' => 'master'], function() {
        Route::resource('ajax-master-satuan','MasterSatuanAjaxController');
        Route::resource('ajax-master-kamar','MasterKamarAjaxController');
        Route::resource('ajax-master-layanan','MasterLayananAjaxController');
        Route::resource('ajax-master-user','MasterUserAjaxController');
        Route::resource('ajax-master-slider', 'MasterSliderAjaxController');
    });

    Route::group(['prefix' => 'transaksi'], function() {
        Route::resource('ajax-master-transaksi-kamar', 'MasterTransaksiKamarAjaxController');
    });

    Route::group(['prefix' => 'kontak'], function() {
        Route::resource('ajax-kontak', 'KontakAjaxController');
    });

    //table
    Route::get('/ajax/tabel-ajax-kategori-kamar', 'KategoriKamarAjaxController@dataTable')->name('table.ajax.kategori.kamar');
    Route::get('/ajax/tabel-ajax-kategori-layanan', 'KategoriLayananAjaxController@dataTable')->name('table.ajax.kategori.layanan');
    Route::get('/ajax/tabel-ajax-satuan', 'MasterSatuanAjaxController@dataTable')->name('table.ajax.satuan');
    Route::get('/ajax/tabel-ajax-kamar', 'MasterKamarAjaxController@dataTable')->name('table.ajax.master.kamar');
    Route::get('/ajax/tabel-ajax-layanan', 'MasterLayananAjaxController@dataTable')->name('table.ajax.master.layanan');
    Route::get('/ajax/tabel-ajax-slider', 'MasterSliderAjaxController@dataTable')->name('table.ajax.master.slider');
    Route::get('/ajax/tabel-ajax.user', 'MasterUserAjaxController@dataTable')->name('table.ajax.master.user');
    Route::get('/ajax/tabel-ajax-kontak', 'KontakAjaxController@dataTable')->name('table.ajax.kontak');
    Route::get('/ajax/tabel-ajax-transaksi-kamar', 'MasterTransaksiKamarAjaxController@dataTable')->name('table.ajax.transaksi.kamar');

    //lain-lain
    Route::post('/dapatkan-info-kategori-kamar', 'KategoriKamarAjaxController@dapatkanInfoKategoriKamar');
    Route::post('/dapatkan-data-kamar', 'MasterKamarAjaxController@dapatkanDataKamar');
    Route::post('/dapatkan-data-layanan', 'MasterLayananAjaxController@dapatkanDataLayanan');
    Route::post('/dapatkan-data-user', 'MasterUserAjaxController@dapatkanDataUser');
    Route::post('/dapatkan-data-slider', 'MasterSliderAjaxController@dapatkanDataSlider');
    Route::post('/cari-detail-kamar', 'KategoriKamarAjaxController@cariDetailKamar');
    Route::post('/dapatkan-data-tipe-transaksi', 'MasterTransaksiKamarAjaxController@dapatkanDataTipeTransaksi');
    Route::post('/validasi-detail-transaksi', 'MasterTransaksiKamarAjaxController@validasiDetailTransaksi');
    Route::post('/dapatkan-data-transaksi-user', 'MasterTransaksiKamarAjaxController@dapatkanDataTransaksiUser');
    Route::post('/dapatkan-data-transaksi-detail', 'MasterTransaksiKamarAjaxController@dapatkanDataTransaksiDetail');

    //print
    Route::get('/cetak-transaksi-kamar/{id}/cetak-deskjet', 'MasterTransaksiKamarAjaxController@cetakDeskjet')->name('ajax-master-transaksi-kamar.cetak.deskjet');
    Route::get('/testing-laravel-javascript', 'MasterKamarAjaxController@testingLaravelJavascript');
});



Route::group(['middleware' => ['auth']], function() {
    Route::get('/logout', 'WebController@logout')->name('logout');
});

Route::get('/test', function () {
    $x = 1;
    $y = 2;
    $z = 3;
    return 'test';
});

Route::get('tanggal', function() {
    $date = date("D M d, Y G:i");
    return formatTanggal($date);
});

app/Kamar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Kamar extends Model
{
    protected $table = 'kamar';
    protected $fillable = ['kategori_kamar_id', 'nomor_kamar', 'lantai',
        'keterangan', 'status', 'gambar'];
    public $timestamps = false;

    public function kategori_kamar()
    {
        return $this->belongsTo(KategoriKamar::class);
    }

    public function dapatkanKamarKosong($kategoriKamar) {
        $kamarKosong = DB::raw("SELECT * FROM Kamar WHERE STATUS='available' AND kategori_kamar_id = 1");

    }
}

resources/views/admin/master/kamar/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['ajax-master-kamar.update', $model->id] : 'ajax-master-kamar.store',
    'method' => $model->exists ? 'PUT' : 'POST',
    'novalidate' => 'novalidate',
    'files' => 'true'
]) !!}

<div class="card mb-2">
    <div class="card-header bg-dark">
        <h6 class="font-weight-bold">Input Data Kamar</h6>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="col-md-12 col-lg-6">
                <div class="form-group">
                    {!! Form::select('kategori_kamar_id', $listKategoriKamar, null, ['id' => 'kategori_kamar_id',
                        'class' => 'form-control form-control-sm']) !!}
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-6">
                            {!! Form::number('nomor_kamar', null, ['class' => 'form-control form-control-sm',
                            'id' => 'nomor_kamar', 'min' => 0, 'max' => '999',
                            'placeholder' => 'Masukkan Nomor Kamar']) !!}
                        </div>
                        <div class="col-6">
                            {!! Form::number('lantai', null, ['class' => 'form-control form-control-sm',
                            'id' => 'lantai', 'min' => 0, 'max' => '99',
                            'placeholder' => 'Masukkan Lantai Kamar']) !!}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::textarea('keterangan', null, ['id' => 'keterangan', 'placeholder' => 'Masukkan Keterangan (boleh dikosongkan)',
                    'class' => 'form-control form-control-sm', 'rows' => 3]) !!}
                </div>
                <div class="form-group">

                    {!! Form::select('status', $listStatus, null, ['id' => 'status', 'class' => 'form-control form-control-sm']) !!}
                </div>
                <div class="form-group">
                    {!! Form::file('file', ['id' => 'file', 'class' => 'form-control form-control-sm']) !!}
                </div>
                @if($model->exists)
                    {{ Form::hidden('nama_file_lama', $model->gambar) }}
                @endif
                <div class="card">
                    <div class="card-header bg-dark">
                    <h6 class="font-weight-bold">Gambar Kamar</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <img id="data_gambar" src="{{ url('/images/kamar/room-unknown.jpg') }}" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-lg-6">
                <div class="card">
                    <div class="card-header bg-dark">
                        <h6 class="font-weight-bold">Data Kategori Kamar</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Nama</label></div>
                            <div class="col-8">{!! Form::text('data_nama', null, ['class' => 'form-control form-control-sm',
                                'disabled' => 'disabled']) !!}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Harga / malam</label></div>
                            <div class="col-8">{!! Form::text('data_harga_permalam', null, ['class' => 'form-control form-control-sm',
                                'disabled' => 'disabled']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Jumlah dewasa</label></div>
                            <div class="col-8">{!! Form::text('data_jumlah_dewasa', null, ['class' => 'form-control form-control-sm',
                                'disabled' => 'disabled']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Jumlah anak</label></div>
                            <div class="col-8">{!! Form::text('data_jumlah_anak', null, ['class' => 'form-control form-control-sm',
                                'disabled' => 'disabled']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Jumlah bed</label></div>
                            <div class="col-8">{!! Form::text('data_bed', null, ['class' => 'form-control form-control-sm',
                                'disabled' => 'disabled']) !!}</div>
                        </div>
                        <div class="row">
                            <div class="col-4"><label class="label col-form-label-sm">Keterangan</label></div>
                            <div class="col-8">{!! Form::textarea('data_keterangan', null, ['class' => 'form-control form-control-sm',
                                'disabled' => 'disabled', 'rows' => 3]) !!}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!}

resources/views/admin/master/kamar/index.blade.php
@extends('layouts.admin')
@section('title', 'Data Master Kamar')

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card border-danger">
            <div class="card-header">
                <h3 class="card-title">List Kamar</h3>
                <div class="card-tools">
                    <a class="btn btn-sm btn-success btn-tampil-modal" data-toggle="modal" tipe="tambah" 
                        judul="Tambah Kamar Baru" ukuran="besar"
                    href="{{ route('ajax-master-kamar.create') }}">
                        <i class="fa fa-plus"></i></a>
                </div>
            </div>
            <div class="card-body">
                <table id="dataTable" class="table table-sm table-hover tabel-master-kamar">
                    <thead>
                        <tr>
                            <th>Gambar</th>
                            <th>Nomor</th>
                            <th>Kategori</th>
                            <th>Harga</th>
                            <th>Lantai</th>
                            <th>Status</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        function tampilInfoKategoriKamar(kategoriId) {
            $.ajaxSetup({
                headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $.ajax({
                url: '/admin/dapatkan-info-kategori-kamar',
                data: { kategoriId },
                async: false,
                type: 'POST',
                success: function(res) {
                    $('input[name=data_nama]').val(res.nama);
                    $('input[name=data_harga_permalam]').val(accounting.formatMoney(res.harga_permalam, 'Rp ', 2, ',', '.'));
                    $('input[name=data_jumlah_dewasa]').val(res.jumlah_dewasa + ' orang');
                    $('input[name=data_jumlah_anak]').val(res.jumlah_anak + ' anak');
                    $('input[name=data_bed]').val(res.jumlah_bed + ' bed');
                    $('input[name=data_keterangan]').val(res.keterangan);
                },
                error: function(err) {
                    console.log(err);
                }
            });
        }

        var model = {!! json_encode($test) !!};
        $(document).ready(function() {
            
            $('#dataTable').DataTable({
                autoWidth: false,
                serverSide: true,
                processing: true,
                responsive: true,
                ajax: "{{ route('table.ajax.master.kamar') }}",
                columns: [
                    { data: 'gambar', nama: 'gambar', render:function(data, tipe, row) {
                        return "<img src='/images/kamar/" + data + "'>";
                    }, 
                    orderable: false },
                    { data: 'nomor_kamar', name: 'nomor_kamar' },
                    { data: 'kategori_kamar', name: 'kategori_kamar' },
                    { data: 'harga', name: 'harga', render: function(data, tipe, row) {
                        return 'Rp ' + formatAngka(data.toString()) + ' /mlm';
                    } },
                    { data: 'lantai', nama: 'lantai' },
                    { data: 'status', nama: 'status' },
                    { data: 'aksi', name: 'aksi' }
                ],
                language: {
                    lengthMenu: 'Tampil _MENU_ rekord per halaman',
                    info: 'Tampil hal _PAGE_ dari _PAGES_',
                    processing: 'Sedang memproses...',
                    search: 'Cari',
                    zeroRecords: 'Tidak ditemukan rekord',
                    paginate: {
                        first: '<<',
                        last: '>>',
                        next: '>',
                        previous: '<',
                    },
                    infoFiltered: "( filter dari _MAX_ jumlah rekord )"
                }
            })

            $('body').on('change', '#kategori_kamar_id', function(e) {
                e.preventDefault();
                if ($(this).val() !== '') {
                    var kategoriId = $(this).val();
                    tampilInfoKategoriKamar(kategoriId);
                }
            });

            $('body').on('change', '#file', function(E) {
                bacaUrl(this);
            });

            $('#modal').on('shown.bs.modal', function(e){
                var status = $('#modal').attr('tipe');
                if (status === 'edit') {
                    var kamarId = $('#modal').attr('kode');
                    var kategoriKamarId;
                    var nomorKamar;
                    var lantai;
                    var keterangan;
                    var status;
                    var gambar;
                    
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    //cari data kamar
                    $.ajax({
                        url: '/admin/dapatkan-data-kamar',
                        data: { kamarId },
                        type: 'POST',
                        success: function(res) {
                            var kamar = res;
                            kamarId = kamar.id;
                            kategoriKamarId = kamar.kategori_kamar_id;
                            nomorKamar = kamar.nomor_kamar;
                            lantai = kamar.lantai;
                            keterangan = kamar.keterangan;
                            status = kamar.status;
                            gambar = kamar.gambar;
                            $('#data_gambar').attr('src', '/images/kamar/' + gambar);
                            tampilInfoKategoriKamar(kategoriKamarId);
                        },
                        error: function(e) {
                            console.log(e);
                        }
                    });
<<<<<<< HEAD
                }               
=======
                }
            });

            $('body').on('change', '#file', function(E) {
                bacaUrl(this);
            });

            $('#modal').on('shown.bs.modal', function(e){
                console.log(windowvar.model);
                var status = $('#modal').attr('tipe');
                if(status === 'edit') {
                    debugger;
                    var kamarId = $('#modal').attr('kode');
                    var kategoriKamar;
                    var nomorKamar;
                    var lantai;
                    var keterangan;
                    var status;
                    var gambar;

                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });

                    //cari data kategori kamar
                    $.ajax({ 
                        url: '/dapatkan-info-kategori-kamar',
                        data: { },
                        async: false,
                        type: "POST",
                        success: function(data){
                            var produk = data;
                            id = produk.id;
                            satuanId = produk.satuan_id;
                            merekId = produk.merek_id;
                            supplierId = produk.supplier_id;
                            harga = produk.harga;
                            harga_beli = produk.harga_beli;
                            gambar = produk.gambar;

                            if(produk.diskon === null) {
                                diskon = 0;
                            } else {
                                diskon = produk.diskon;
                            }

                            $.ajax({ 
                                url: '/cari-nama-satuan',
                                data: { satuanId },
                                type: "POST",
                                success: function(res){
                                    $('#data_satuan_nama').val(res);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });
                            
                            $.ajax({ 
                                url: '/hitung-harga-diskon',
                                data: { harga, diskon },
                                type: "POST",
                                success: function(res){
                                    var hargaDiskon = res;
                                    $('#data_harga_diskon').val(accounting.formatMoney(hargaDiskon, 'Rp ', 2, ',', '.'));  
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            $.ajax({ 
                                url: "/cari-merek-logo",
                                data: { merekId },
                                type: "POST",
                                success: function(data){
                                    var gambar = data;
                                    $('#data_gambar_merek').attr('src', 'web/img/' + gambar);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            $.ajax({ 
                                url: "/cari-data-supplier",
                                data: { supplierId },
                                type: "POST",
                                success: function(data){
                                    $('#data_supplier_alamat').val(data.alamat);
                                    $('#data_supplier_kota').val(data.kota.nama);
                                    $('#data_supplier_pic').val(data.pic);
                                    $('#data_supplier_telpon').val(data.no_telpon);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            $.ajax({ 
                                url: "/cari-gambar-produk",
                                data: { id },
                                type: "POST",
                                success: function(data){
                                    var gambar = data;
                                    $('#data_gambar').attr('src', 'web/img/produk/' + gambar);
                                },
                                error: function(error) {
                                    console.log(error);
                                }
                            });

                            //bikin hidden input untuk harga dan harga beli
                            // bikinHiddenInput('hidden_harga', harga);
                            // bikinHiddenInput('hidden_harga_beli', harga_beli);
                            
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    }); 
                }
>>>>>>> master
            });
        });
    </script>
@endpush

resources/views/admin/master/kamar/tampil.blade.php
<div class="row">
    <div class="col-md-6 col-sm-12">
        <div class="card">
            <div class="card-header bg-primary">
                <h6 class="font-weight-bold">Data Transaksi</h6>
            </div>
            <div class="card-body">
                <table class="table table-borderless tabel-master-show tabel-tampil-kamar">
                    <tbody>
                        <tr>
                            <td>Nomor Kamar</td>
                            <td>:</td>
                            <td>{{ $model->nomor_kamar }}</td>
                        </tr>
                        <tr>
                            <td>Kategori Kamar</td>
                            <td>:</td>
                            <td>{{ $model->kategori_kamar->nama }}</td>
                        </tr>
                        <tr>
                            <td>Lantai</td>
                            <td>:</td>
                            <td>{{ $model->lantai }}</td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td>:</td>
                            <td>{{ $model->status }}</td>
                        </tr>
                        <tr>
                            <td>Keterangan</td>
                            <td>:</td>
                            <td>
                                @if($model->keterangan === null)
                                    -
                                @else
                                    {{ $model->keterangan }}
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td>Gambar</td>
                            <td>:</td>
                            <td><img src="{{ url('/images/kamar/' . $model->gambar) }}"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <div class="card">
            <div class="card-header bg-success">
                <h6 class="font-weight-bold">Data Kategori Kamar</h6>
            </div>
            <div class="card-body">
                <table class="table table-borderless tabel-master-show">
                    <tr>
                        <td>Nama</td>
                        <td>:</td>
                        <td>{{ $model->kategori_kamar->nama }}</td>
                    </tr>
                    <tr>
                        <td>Harga</td>
                        <td>:</td>
                        <td>Rp @formatUang($model->kategori_kamar->harga_permalam)</td>
                    </tr>
                    <tr>
                        <td>Jumlah Dewasa</td>
                        <td>:</td>
                        <td>{{ $model->kategori_kamar->jumlah_dewasa }} orang</td>
                    </tr>
                    <tr>
                        <td>Jumlah Anak</td>
                        <td>:</td>
                        <td>{{ $model->kategori_kamar->jumlah_anak }} anak</td>
                    </tr>
                    <tr>
                        <td>Jumlah Bed</td>
                        <td>:</td>
                        <td>{{ $model->kategori_kamar->jumlah_bed }} bed</td>
                    </tr>
                    <tr>
                        <td>Keterangan</td>
                        <td>:</td>
                        <td>
                            @if($model->kategori_kamar->keterangan === null)
                                -
                            @else
                                {{ $model->kategori_kamar->keterangan }}</td>
                            @endif
                        </tr>
                </table>
            </div>
        </div>
    </div>
</div>